ボーリングプログラムの作成完了
shibainurou/ruby-practices pull request #3
Opened 2022-06-05 15:47 UTC by shibainurou

プログラムの作成が完了しました。
レビューをお願いします。

2022-06-10 19:46 UTC, komagata requested changes

2022-06-10 19:46 UTC, komagata commented on 04.bowling/bowling.rb
> +  }.freeze
これはkeyとvalueがほとんど同じなので全部のパターンを自分で用意しなくても変換できるかもです〜

2022-06-10 19:46 UTC, komagata commented on 04.bowling/bowling.rb
> +  end
```suggestion
  def strike(point)
    point == 'X'
  end
```

でいいかも？です〜

2022-06-11 10:00 UTC, shibainurou commented on 04.bowling/bowling.rb
> +  end
Rubyのnullはぬるぽにならずfalseになるので、こちらの方がシンプルですね。
ご提案のように修正しました。

2022-06-11 10:03 UTC, shibainurou commented on 04.bowling/bowling.rb
> +  }.freeze
freeneはリテラルにしか使えないものと思っていました。
ArrayのメソッドなのでArrayであれば使用可能なんですね！
動的作成したハッシュをfreezeするように修正しました。

2022-06-11 10:04 UTC, shibainurou commented
@komagata 
指摘事項を修正しました。再レビューをお願いします！
フレーム数がマジックナンバーになっていたので合わせて修正しました。

2022-06-14 14:59 UTC, komagata commented on 04.bowling/bowling.rb
> +  }.freeze
全てのパターンを変数として持つとそれだけメモリを余計に確保することになってしまいます。

これらはあらかじめ全パターン用意しなくても変換することで対応することができると思います〜。

2022-06-14 15:02 UTC, komagata requested changes

2022-06-14 15:02 UTC, komagata commented on 04.bowling/bowling.rb
> +  def spare(point1, point2)
booleanを返すメソッドはメソッド名の最後を`?`にするとわかりやすいかもです〜
rubyでは基本的にメソッド名をそのようにします〜。

2022-06-19 13:17 UTC, shibainurou commented on 04.bowling/bowling.rb
> +  }.freeze
変換テーブルをやめて、`if == 'X'`と`to_i`で変換するように修正しました。

2022-06-19 13:17 UTC, shibainurou commented
@komagata 
指摘事項を修正しました。再レビューをお願いします。

2022-06-19 13:18 UTC, shibainurou commented on 04.bowling/bowling.rb
> +  def spare(point1, point2)
ありがとうございます！ご指摘のように修正しました。

2022-06-21 18:50 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-11-28 12:41 UTC, merged